package chrometool

// The runes correspond to the once used in chromedb/chromedb/kb in keys.go
var keyStrToRune = map[string]rune{
	"BackSpace":  '\b',
	"Tab":        '\t',
	"Enter":      '\n',
	"Return":     '\r',
	"Escape":     '\u001b',
	" ":          ' ',
	"!":          '!',
	"\"":         '"',
	"#":          '#',
	"$":          '$',
	"%":          '%',
	"&":          '&',
	"'":          '\'',
	"(":          '(',
	")":          ')',
	"*":          '*',
	"+":          '+',
	",":          ',',
	"-":          '-',
	".":          '.',
	"/":          '/',
	"0":          '0',
	"1":          '1',
	"2":          '2',
	"3":          '3',
	"4":          '4',
	"5":          '5',
	"6":          '6',
	"7":          '7',
	"8":          '8',
	"9":          '9',
	":":          ':',
	";":          ';',
	"<":          '<',
	"=":          '=',
	">":          '>',
	"?":          '?',
	"@":          '@',
	"A":          'A',
	"B":          'B',
	"C":          'C',
	"D":          'D',
	"E":          'E',
	"F":          'F',
	"G":          'G',
	"H":          'H',
	"I":          'I',
	"J":          'J',
	"K":          'K',
	"L":          'L',
	"M":          'M',
	"N":          'N',
	"O":          'O',
	"P":          'P',
	"Q":          'Q',
	"R":          'R',
	"S":          'S',
	"T":          'T',
	"U":          'U',
	"V":          'V',
	"W":          'W',
	"X":          'X',
	"Y":          'Y',
	"Z":          'Z',
	"[":          '[',
	"\\":         '\\',
	"]":          ']',
	"^":          '^',
	"_":          '_',
	"`":          '`',
	"a":          'a',
	"b":          'b',
	"c":          'c',
	"d":          'd',
	"e":          'e',
	"f":          'f',
	"g":          'g',
	"h":          'h',
	"i":          'i',
	"j":          'j',
	"k":          'k',
	"l":          'l',
	"m":          'm',
	"n":          'n',
	"o":          'o',
	"p":          'p',
	"q":          'q',
	"r":          'r',
	"s":          's',
	"t":          't',
	"u":          'u',
	"v":          'v',
	"w":          'w',
	"x":          'x',
	"y":          'y',
	"z":          'z',
	"{":          '{',
	"|":          '|',
	"}":          '}',
	"~":          '~',
	"Delete":     '\u007f',
	"¥":          '¥',
	"Alt_L":      '\u0102',
	"Alt_R":      '\u0102',
	"Alt":        '\u0102',
	"Caps_Lock":  '\u0104',
	"CapsLock":   '\u0104',
	"Control":    '\u0105',
	"Control_L":  '\u0105',
	"Control_R":  '\u0105',
	"Hyper":      '\u0108',
	"Hyper_L":    '\u0108',
	"Hyper_R":    '\u0108',
	"Meta":       '\u0109',
	"Meta_L":     '\u0109',
	"Meta_R":     '\u0109',
	"NumLock":    '\u010a',
	"ScrollLock": '\u010c',
	"Shift":      '\u010d',
	"Shift_L":    '\u010d',
	"Shift_R":    '\u010d',
	"Super":      '\u010e',
	"Super_L":    '\u010e',
	"Super_R":    '\u010e',
	"downarrow":  '\u0301',
	"Down":       '\u0301',
	"leftarrow":  '\u0302',
	"Left":       '\u0302',
	"rightarrow": '\u0303',
	"Right":      '\u0303',
	"uparrow":    '\u0304',
	"Up":         '\u0304',
	"End":        '\u0305',
	"Home":       '\u0306',
	"PageDown":   '\u0307',
	"PageUp":     '\u0308',
	"Insert":     '\u0407',

	// '\u0402': {"Copy", "Copy", "", "", 0, 0, false, false},
	// '\u0404': {"Cut", "Cut", "", "", 0, 0, false, false},
	// '\u0408': {"Paste", "Paste", "", "", 0, 0, false, false},
	// '\u0409': {"Redo", "Redo", "", "", 0, 0, false, false},
	// '\u040a': {"Undo", "Undo", "", "", 0, 0, false, false},
	// '\u0502': {"Again", "Again", "", "", 0, 0, false, false},
	// '\u0504': {"Abort", "Cancel", "", "", 3, 3, false, false},
	// '\u0505': {"ContextMenu", "ContextMenu", "", "", 93, 93, false, false},
	// '\u0507': {"Find", "Find", "", "", 0, 0, false, false},
	// '\u0508': {"Help", "Help", "", "", 47, 47, false, false},
	// '\u0509': {"Pause", "Pause", "", "", 19, 19, false, false},
	// '\u050b': {"Props", "Props", "", "", 0, 0, false, false},
	// '\u050c': {"Select", "Select", "", "", 41, 41, false, false},
	// '\u050d': {"ZoomIn", "ZoomIn", "", "", 0, 0, false, false},
	// '\u050e': {"ZoomOut", "ZoomOut", "", "", 0, 0, false, false},
	// '\u0601': {"BrightnessDown", "BrightnessDown", "", "", 216, 0, false, false},
	// '\u0602': {"BrightnessUp", "BrightnessUp", "", "", 217, 0, false, false},
	// '\u0604': {"Eject", "Eject", "", "", 0, 0, false, false},
	// '\u0605': {"LogOff", "LogOff", "", "", 0, 0, false, false},
	// '\u0606': {"Power", "Power", "", "", 152, 0, false, false},
	// '\u0608': {"PrintScreen", "PrintScreen", "", "", 44, 44, false, false},
	// '\u060b': {"WakeUp", "WakeUp", "", "", 0, 0, false, false},
	// '\u0705': {"Convert", "Convert", "", "", 28, 28, false, false},
	// '\u070b': {"KeyboardLayoutSelect", "ModeChange", "", "", 0, 0, false, false},
	// '\u070d': {"NonConvert", "NonConvert", "", "", 29, 29, false, false},
	// '\u0711': {"Lang1", "HangulMode", "", "", 21, 21, false, false},
	// '\u0712': {"Lang2", "HanjaMode", "", "", 25, 25, false, false},
	// '\u0716': {"Lang4", "Hiragana", "", "", 0, 0, false, false},
	// '\u0718': {"KanaMode", "KanaMode", "", "", 21, 21, false, false},
	// '\u071a': {"Lang3", "Katakana", "", "", 0, 0, false, false},
	// '\u071d': {"Lang5", "ZenkakuHankaku", "", "", 0, 0, false, false},
	// '\u0801': {"F1", "F1", "", "", 112, 112, false, false},
	// '\u0802': {"F2", "F2", "", "", 113, 113, false, false},
	// '\u0803': {"F3", "F3", "", "", 114, 114, false, false},
	// '\u0804': {"F4", "F4", "", "", 115, 115, false, false},
	// '\u0805': {"F5", "F5", "", "", 116, 116, false, false},
	// '\u0806': {"F6", "F6", "", "", 117, 117, false, false},
	// '\u0807': {"F7", "F7", "", "", 118, 118, false, false},
	// '\u0808': {"F8", "F8", "", "", 119, 119, false, false},
	// '\u0809': {"F9", "F9", "", "", 120, 120, false, false},
	// '\u080a': {"F10", "F10", "", "", 121, 121, false, false},
	// '\u080b': {"F11", "F11", "", "", 122, 122, false, false},
	// '\u080c': {"F12", "F12", "", "", 123, 123, false, false},
	// '\u080d': {"F13", "F13", "", "", 124, 124, false, false},
	// '\u080e': {"F14", "F14", "", "", 125, 125, false, false},
	// '\u080f': {"F15", "F15", "", "", 126, 126, false, false},
	// '\u0810': {"F16", "F16", "", "", 127, 127, false, false},
	// '\u0811': {"F17", "F17", "", "", 128, 128, false, false},
	// '\u0812': {"F18", "F18", "", "", 129, 129, false, false},
	// '\u0813': {"F19", "F19", "", "", 130, 130, false, false},
	// '\u0814': {"F20", "F20", "", "", 131, 131, false, false},
	// '\u0815': {"F21", "F21", "", "", 132, 132, false, false},
	// '\u0816': {"F22", "F22", "", "", 133, 133, false, false},
	// '\u0817': {"F23", "F23", "", "", 134, 134, false, false},
	// '\u0818': {"F24", "F24", "", "", 135, 135, false, false},
	// '\u0a01': {"Close", "Close", "", "", 0, 0, false, false},
	// '\u0a02': {"MailForward", "MailForward", "", "", 0, 0, false, false},
	// '\u0a03': {"MailReply", "MailReply", "", "", 0, 0, false, false},
	// '\u0a04': {"MailSend", "MailSend", "", "", 0, 0, false, false},
	// '\u0a05': {"MediaPlayPause", "MediaPlayPause", "", "", 179, 179, false, false},
	// '\u0a07': {"MediaStop", "MediaStop", "", "", 178, 178, false, false},
	// '\u0a08': {"MediaTrackNext", "MediaTrackNext", "", "", 176, 176, false, false},
	// '\u0a09': {"MediaTrackPrevious", "MediaTrackPrevious", "", "", 177, 177, false, false},
	// '\u0a0a': {"New", "New", "", "", 0, 0, false, false},
	// '\u0a0b': {"Open", "Open", "", "", 43, 43, false, false},
	// '\u0a0c': {"Print", "Print", "", "", 0, 0, false, false},
	// '\u0a0d': {"Save", "Save", "", "", 0, 0, false, false},
	// '\u0a0e': {"SpellCheck", "SpellCheck", "", "", 0, 0, false, false},
	// '\u0a0f': {"AudioVolumeDown", "AudioVolumeDown", "", "", 174, 174, false, false},
	// '\u0a10': {"AudioVolumeUp", "AudioVolumeUp", "", "", 175, 175, false, false},
	// '\u0a11': {"AudioVolumeMute", "AudioVolumeMute", "", "", 173, 173, false, false},
	// '\u0b01': {"LaunchApp2", "LaunchApplication2", "", "", 183, 183, false, false},
	// '\u0b02': {"LaunchCalendar", "LaunchCalendar", "", "", 0, 0, false, false},
	// '\u0b03': {"LaunchMail", "LaunchMail", "", "", 180, 180, false, false},
	// '\u0b04': {"MediaSelect", "LaunchMediaPlayer", "", "", 181, 181, false, false},
	// '\u0b05': {"LaunchMusicPlayer", "LaunchMusicPlayer", "", "", 0, 0, false, false},
	// '\u0b06': {"LaunchApp1", "LaunchApplication1", "", "", 182, 182, false, false},
	// '\u0b07': {"LaunchScreenSaver", "LaunchScreenSaver", "", "", 0, 0, false, false},
	// '\u0b08': {"LaunchSpreadsheet", "LaunchSpreadsheet", "", "", 0, 0, false, false},
	// '\u0b09': {"LaunchWebBrowser", "LaunchWebBrowser", "", "", 0, 0, false, false},
	// '\u0b0c': {"LaunchContacts", "LaunchContacts", "", "", 0, 0, false, false},
	// '\u0b0d': {"LaunchPhone", "LaunchPhone", "", "", 0, 0, false, false},
	// '\u0b0e': {"LaunchAssistant", "LaunchAssistant", "", "", 153, 0, false, false},
	// '\u0c01': {"BrowserBack", "BrowserBack", "", "", 166, 166, false, false},
	// '\u0c02': {"BrowserFavorites", "BrowserFavorites", "", "", 171, 171, false, false},
	// '\u0c03': {"BrowserForward", "BrowserForward", "", "", 167, 167, false, false},
	// '\u0c04': {"BrowserHome", "BrowserHome", "", "", 172, 172, false, false},
	// '\u0c05': {"BrowserRefresh", "BrowserRefresh", "", "", 168, 168, false, false},
	// '\u0c06': {"BrowserSearch", "BrowserSearch", "", "", 170, 170, false, false},
	// '\u0c07': {"BrowserStop", "BrowserStop", "", "", 169, 169, false, false},
	// '\u0d0a': {"ChannelDown", "ChannelDown", "", "", 0, 0, false, false},
	// '\u0d0b': {"ChannelUp", "ChannelUp", "", "", 0, 0, false, false},
	// '\u0d12': {"ClosedCaptionToggle", "ClosedCaptionToggle", "", "", 0, 0, false, false},
	// '\u0d15': {"Exit", "Exit", "", "", 0, 0, false, false},
	// '\u0d22': {"Guide", "Guide", "", "", 0, 0, false, false},
	// '\u0d25': {"Info", "Info", "", "", 0, 0, false, false},
	// '\u0d2c': {"MediaFastForward", "MediaFastForward", "", "", 0, 0, false, false},
	// '\u0d2d': {"MediaLast", "MediaLast", "", "", 0, 0, false, false},
	// '\u0d2f': {"MediaPlay", "MediaPlay", "", "", 0, 0, false, false},
	// '\u0d30': {"MediaRecord", "MediaRecord", "", "", 0, 0, false, false},
	// '\u0d31': {"MediaRewind", "MediaRewind", "", "", 0, 0, false, false},
	// '\u0d43': {"LaunchControlPanel", "Settings", "", "", 154, 0, false, false},
	// '\u0d4e': {"ZoomToggle", "ZoomToggle", "", "", 251, 251, false, false},
	// '\u0e02': {"AudioBassBoostToggle", "AudioBassBoostToggle", "", "", 0, 0, false, false},
	// '\u0f02': {"SpeechInputToggle", "SpeechInputToggle", "", "", 0, 0, false, false},
	// '\u1001': {"SelectTask", "AppSwitch", "", "", 0, 0, false, false},
	//"Fn":      '\u0106',
	//"FnLock":	 '\u0107',
	//"NumpadClear": '\u0401',
}
